### PR TITLE
Add tip jar plugin

### PR DESCRIPTION
**Pull request by thomash-acinq**
Very basic plugin demonstrating how to handle offers from the merchant's side. This plugin just creates a simple "tip" offer and accept all payments.

### CODE REVIEW

**Review by t-bast — DISMISSED** [review]
LGTM, nice to have this for the eclair release.

**Comment by thomash-acinq** [comment]
I had to fix a merge conflict.

**Review by t-bast — APPROVED** [review]

**Comment by t-bast** [comment]
Don't forget to do a squash-merge next time, you used a standard merge so the code is actually scattered in multiple commits (without a proper commit message).

**Comment by t-bast** [comment]
No big deal don't worry, Github isn't always very clear on what will happen when merging...

**Pull request merged**
